/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/tuenti/secrets-manager/pkg/apis/secretsmanager/v1alpha1"
	scheme "github.com/tuenti/secrets-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecretDefinitionsGetter has a method to return a SecretDefinitionInterface.
// A group's client should implement this interface.
type SecretDefinitionsGetter interface {
	SecretDefinitions(namespace string) SecretDefinitionInterface
}

// SecretDefinitionInterface has methods to work with SecretDefinition resources.
type SecretDefinitionInterface interface {
	Create(*v1alpha1.SecretDefinition) (*v1alpha1.SecretDefinition, error)
	Update(*v1alpha1.SecretDefinition) (*v1alpha1.SecretDefinition, error)
	UpdateStatus(*v1alpha1.SecretDefinition) (*v1alpha1.SecretDefinition, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SecretDefinition, error)
	List(opts v1.ListOptions) (*v1alpha1.SecretDefinitionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretDefinition, err error)
	SecretDefinitionExpansion
}

// secretDefinitions implements SecretDefinitionInterface
type secretDefinitions struct {
	client rest.Interface
	ns     string
}

// newSecretDefinitions returns a SecretDefinitions
func newSecretDefinitions(c *SecretsmanagerV1alpha1Client, namespace string) *secretDefinitions {
	return &secretDefinitions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretDefinition, and returns the corresponding secretDefinition object, and an error if there is any.
func (c *secretDefinitions) Get(name string, options v1.GetOptions) (result *v1alpha1.SecretDefinition, err error) {
	result = &v1alpha1.SecretDefinition{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretdefinitions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretDefinitions that match those selectors.
func (c *secretDefinitions) List(opts v1.ListOptions) (result *v1alpha1.SecretDefinitionList, err error) {
	result = &v1alpha1.SecretDefinitionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretDefinitions.
func (c *secretDefinitions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a secretDefinition and creates it.  Returns the server's representation of the secretDefinition, and an error, if there is any.
func (c *secretDefinitions) Create(secretDefinition *v1alpha1.SecretDefinition) (result *v1alpha1.SecretDefinition, err error) {
	result = &v1alpha1.SecretDefinition{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretdefinitions").
		Body(secretDefinition).
		Do().
		Into(result)
	return
}

// Update takes the representation of a secretDefinition and updates it. Returns the server's representation of the secretDefinition, and an error, if there is any.
func (c *secretDefinitions) Update(secretDefinition *v1alpha1.SecretDefinition) (result *v1alpha1.SecretDefinition, err error) {
	result = &v1alpha1.SecretDefinition{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretdefinitions").
		Name(secretDefinition.Name).
		Body(secretDefinition).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *secretDefinitions) UpdateStatus(secretDefinition *v1alpha1.SecretDefinition) (result *v1alpha1.SecretDefinition, err error) {
	result = &v1alpha1.SecretDefinition{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretdefinitions").
		Name(secretDefinition.Name).
		SubResource("status").
		Body(secretDefinition).
		Do().
		Into(result)
	return
}

// Delete takes name of the secretDefinition and deletes it. Returns an error if one occurs.
func (c *secretDefinitions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretdefinitions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretDefinitions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretdefinitions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched secretDefinition.
func (c *secretDefinitions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretDefinition, err error) {
	result = &v1alpha1.SecretDefinition{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretdefinitions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
