/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/tuenti/secrets-manager/pkg/apis/secretsmanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecretDefinitions implements SecretDefinitionInterface
type FakeSecretDefinitions struct {
	Fake *FakeSecretsmanagerV1alpha1
	ns   string
}

var secretdefinitionsResource = schema.GroupVersionResource{Group: "secretsmanager.tuenti.io", Version: "v1alpha1", Resource: "secretdefinitions"}

var secretdefinitionsKind = schema.GroupVersionKind{Group: "secretsmanager.tuenti.io", Version: "v1alpha1", Kind: "SecretDefinition"}

// Get takes name of the secretDefinition, and returns the corresponding secretDefinition object, and an error if there is any.
func (c *FakeSecretDefinitions) Get(name string, options v1.GetOptions) (result *v1alpha1.SecretDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(secretdefinitionsResource, c.ns, name), &v1alpha1.SecretDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretDefinition), err
}

// List takes label and field selectors, and returns the list of SecretDefinitions that match those selectors.
func (c *FakeSecretDefinitions) List(opts v1.ListOptions) (result *v1alpha1.SecretDefinitionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(secretdefinitionsResource, secretdefinitionsKind, c.ns, opts), &v1alpha1.SecretDefinitionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SecretDefinitionList{}
	for _, item := range obj.(*v1alpha1.SecretDefinitionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested secretDefinitions.
func (c *FakeSecretDefinitions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(secretdefinitionsResource, c.ns, opts))

}

// Create takes the representation of a secretDefinition and creates it.  Returns the server's representation of the secretDefinition, and an error, if there is any.
func (c *FakeSecretDefinitions) Create(secretDefinition *v1alpha1.SecretDefinition) (result *v1alpha1.SecretDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(secretdefinitionsResource, c.ns, secretDefinition), &v1alpha1.SecretDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretDefinition), err
}

// Update takes the representation of a secretDefinition and updates it. Returns the server's representation of the secretDefinition, and an error, if there is any.
func (c *FakeSecretDefinitions) Update(secretDefinition *v1alpha1.SecretDefinition) (result *v1alpha1.SecretDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(secretdefinitionsResource, c.ns, secretDefinition), &v1alpha1.SecretDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretDefinition), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecretDefinitions) UpdateStatus(secretDefinition *v1alpha1.SecretDefinition) (*v1alpha1.SecretDefinition, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(secretdefinitionsResource, "status", c.ns, secretDefinition), &v1alpha1.SecretDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretDefinition), err
}

// Delete takes name of the secretDefinition and deletes it. Returns an error if one occurs.
func (c *FakeSecretDefinitions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(secretdefinitionsResource, c.ns, name), &v1alpha1.SecretDefinition{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecretDefinitions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(secretdefinitionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SecretDefinitionList{})
	return err
}

// Patch applies the patch and returns the patched secretDefinition.
func (c *FakeSecretDefinitions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretDefinition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(secretdefinitionsResource, c.ns, name, data, subresources...), &v1alpha1.SecretDefinition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SecretDefinition), err
}
