/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	secretsmanager_v1alpha1 "github.com/tuenti/secrets-manager/pkg/apis/secretsmanager/v1alpha1"
	versioned "github.com/tuenti/secrets-manager/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tuenti/secrets-manager/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tuenti/secrets-manager/pkg/client/listers/secretsmanager/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SecretDefinitionInformer provides access to a shared informer and lister for
// SecretDefinitions.
type SecretDefinitionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SecretDefinitionLister
}

type secretDefinitionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSecretDefinitionInformer constructs a new informer for SecretDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSecretDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSecretDefinitionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSecretDefinitionInformer constructs a new informer for SecretDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSecretDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretsmanagerV1alpha1().SecretDefinitions(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SecretsmanagerV1alpha1().SecretDefinitions(namespace).Watch(options)
			},
		},
		&secretsmanager_v1alpha1.SecretDefinition{},
		resyncPeriod,
		indexers,
	)
}

func (f *secretDefinitionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSecretDefinitionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *secretDefinitionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&secretsmanager_v1alpha1.SecretDefinition{}, f.defaultInformer)
}

func (f *secretDefinitionInformer) Lister() v1alpha1.SecretDefinitionLister {
	return v1alpha1.NewSecretDefinitionLister(f.Informer().GetIndexer())
}
